name = "jsp_000759_formalization"
version = "0.1.0"
defaultTargets = ["Challenge", "Submission"]

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4"
rev = "5ed2965256430c3649e86755f9576b54eca72435"

[[lean_lib]]
name = "ErdosProblems"
srcDir = "."
roots = ["ErdosProblems.Erdos915"]

[[lean_lib]]
name = "Challenge"
srcDir = "."
roots = ["Challenge"]

[[lean_lib]]
name = "Submission"
srcDir = "."
roots = ["Submission"]
